-- ============================================================
-- TUNISIA WNT — Elite Squad Manager : FULL DATABASE SETUP
-- Run this ONCE in Supabase Dashboard > SQL Editor > New query
-- ============================================================

-- ------------------------------------------------------------
-- PROFILES  (one row per auth user, username is login)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id          uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username    text UNIQUE NOT NULL,
  first_name  text NOT NULL DEFAULT '',
  last_name   text NOT NULL DEFAULT '',
  role        text NOT NULL DEFAULT 'staff' CHECK (role IN ('admin','staff')),
  status      text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','active','suspended')),
  permissions jsonb NOT NULL DEFAULT '{}',
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- username <-> email lookup used by signInUsername()
CREATE TABLE IF NOT EXISTS public.login_emails (
  username text PRIMARY KEY,
  email    text NOT NULL
);

CREATE OR REPLACE FUNCTION public.get_login_email(p_username text)
RETURNS text
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT email FROM public.login_emails WHERE username = lower(p_username) LIMIT 1;
$$;

GRANT EXECUTE ON FUNCTION public.get_login_email(text) TO anon, authenticated, service_role;

-- Auto-register the username->email mapping whenever a profile is created
CREATE OR REPLACE FUNCTION public.on_profile_created()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.login_emails (username, email)
  VALUES (NEW.username, NEW.username || '@placeholder.tunisia-wnt.local')
  ON CONFLICT (username) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_profile_created ON public.profiles;
CREATE TRIGGER trg_profile_created
  AFTER INSERT ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.on_profile_created();

-- ------------------------------------------------------------
-- MEMBERS  (players + coaching staff)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.members (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role              text NOT NULL DEFAULT 'PLAYERS',
  name              text,
  position          text,
  team_category     text,
  club              text,
  foot              text,
  nationality       text,
  languages         jsonb NOT NULL DEFAULT '[]',
  birthdate         text,
  height            numeric,
  goals             text,
  assists           text,
  clean_sheets      integer NOT NULL DEFAULT 0,
  yellow_cards      integer NOT NULL DEFAULT 0,
  red_cards         integer NOT NULL DEFAULT 0,
  suspended         boolean NOT NULL DEFAULT false,
  contract          text,
  nat_matches       text,
  history           jsonb NOT NULL DEFAULT '[]',
  image_url         text,
  image_path        text,
  bio_quote         text,
  league_region     text,
  dual_nationality  boolean NOT NULL DEFAULT false,
  second_nationality text,
  updated_at        timestamptz NOT NULL DEFAULT now()
);

-- Make sure every column exists even if the table was created earlier with a different shape
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS image_path text;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

-- ------------------------------------------------------------
-- MATCHES
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.matches (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  opponent    text,
  match_date  text,
  competition text,
  category    text,
  details     jsonb NOT NULL DEFAULT '{}',
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- ------------------------------------------------------------
-- MEDICAL / SQUAD LAB / AUDIT
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.injuries (
  id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  member_id          bigint REFERENCES public.members(id) ON DELETE CASCADE,
  status             text NOT NULL DEFAULT 'active' CHECK (status IN ('active','recovering','recovered')),
  injury_type        text,
  body_part          text,
  severity           text,
  occurred_on        text,
  expected_return    text,
  notes              text,
  logged_by          uuid,
  logged_by_username text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.squad_templates (
  id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  team_category       text,
  name                text,
  formation           text,
  slots               jsonb NOT NULL DEFAULT '{}',
  created_by          uuid,
  created_by_username text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.activity_log (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  actor      text,
  action     text,
  entity     text,
  entity_id  text,
  details    jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ------------------------------------------------------------
-- STORAGE BUCKET  (player photos)
-- ------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('members', 'members', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- ------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ------------------------------------------------------------
ALTER TABLE public.profiles        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_emails    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.injuries        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.squad_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_log    ENABLE ROW LEVEL SECURITY;

-- Helper: am I an active admin?
-- login_emails: NO policies (reached only via the definer RPC)

-- helper used by admin policies (SECURITY DEFINER => no recursion in RLS)
CREATE OR REPLACE FUNCTION public.current_active_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT coalesce((SELECT role FROM profiles WHERE id = auth.uid()),'') = 'admin'
     AND coalesce((SELECT status FROM profiles WHERE id = auth.uid()),'') = 'active';
$$;

DROP POLICY IF EXISTS "profiles_select_auth" ON public.profiles;
DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
DROP POLICY IF EXISTS "profiles_admin_all" ON public.profiles;
CREATE POLICY "profiles_select_auth" ON public.profiles FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "profiles_admin_all" ON public.profiles FOR ALL USING (public.current_active_admin());

DROP POLICY IF EXISTS "members_select_anon" ON public.members;
DROP POLICY IF EXISTS "members_dml_authenticated" ON public.members;
DROP POLICY IF EXISTS "matches_select_anon" ON public.matches;
DROP POLICY IF EXISTS "matches_dml_authenticated" ON public.matches;
CREATE POLICY "members_select_anon"       ON public.members FOR SELECT USING (true);
CREATE POLICY "members_dml_authenticated" ON public.members FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "matches_select_anon"       ON public.matches FOR SELECT USING (true);
CREATE POLICY "matches_dml_authenticated" ON public.matches FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "injuries_all_auth" ON public.injuries;
DROP POLICY IF EXISTS "squad_templates_all_auth" ON public.squad_templates;
DROP POLICY IF EXISTS "activity_log_all_auth" ON public.activity_log;
CREATE POLICY "injuries_all_auth"         ON public.injuries        FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "squad_templates_all_auth"  ON public.squad_templates FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "activity_log_all_auth"     ON public.activity_log    FOR ALL USING (auth.role() = 'authenticated');

-- ------------------------------------------------------------
-- SEED: demo squad + matches so the portal is instantly usable.
-- Delete or edit these rows from the app once you add real data.
-- ------------------------------------------------------------
INSERT INTO public.members (role,name,position,team_category,club,foot,nationality,languages,birthdate,height,goals,assists,clean_sheets,yellow_cards,red_cards,suspended,contract,nat_matches,history)
SELECT
  'PLAYERS',
  (ARRAY['Sabrine Elloumi','Amani Jlassi','Salima Trabelsi','Nadia Hamdi','Imen Ben Salem','Yasmine Mami','Wissem Bellagha','Fatma Laaroussi','Chaima Boukraa','Mariem Khlifi','Asma Ben Yahia','Sana Cherif','Rim Ben Ayed','Houda Barhoumi','Nour Hachicha','Marwa Dridi','Syrine Bouteraa','Salma Mabrouk'])[i+1],
  (ARRAY['FORWARD','FORWARD','MIDFIELDER','MIDFIELDER','DEFENDER','DEFENDER','GOALKEEPER'])[i%7+1],
  (ARRAY['SENIORS','U20','U17'])[i%3+1],
  (ARRAY['FC Nabeul','ASF Sousse','Club Africain','Cotif Sfax'])[i%4+1],
  (ARRAY['R','L','R'])[i%3+1],
  'Tunisia',
  '["ARABIC","FRENCH"]'::jsonb,
  (15 + i%10)::text || '/0' || (1 + i%3)::text || '/1998',
  163 + (i*2)%8,
  (10 - i%8)::text,
  (5 - i%4)::text,
  0,
  CASE WHEN i%3=0 THEN 1 ELSE 0 END,
  0,
  false,
  '2027',
  (30 - i%10)::text,
  '[]'::jsonb
FROM generate_series(0,17) AS i;

INSERT INTO public.members (role,name,position,team_category,club,foot,nationality,languages,birthdate,height,goals,assists,clean_sheets,yellow_cards,red_cards,suspended,contract,nat_matches,history)
VALUES
  ('COACHES','Hedi Baccar','HEAD COACH','SENIORS','','R','Tunisia','[]'::jsonb,'05/03/1980',0,'0','0',0,0,0,false,'2027','0','[]'::jsonb),
  ('COACHES','Karim Zouaghi','ASSISTANT COACH','SENIORS','','R','Tunisia','[]'::jsonb,'05/03/1980',0,'0','0',0,0,0,false,'2027','0','[]'::jsonb),
  ('COACHES','Leila Mejri','GOALKEEPER COACH','SENIORS','','R','Tunisia','[]'::jsonb,'05/03/1980',0,'0','0',0,0,0,false,'2027','0','[]'::jsonb),
  ('COACHES','Sofien Grira','FITNESS COACH','SENIORS','','R','Tunisia','[]'::jsonb,'05/03/1980',0,'0','0',0,0,0,false,'2027','0','[]'::jsonb),
  ('COACHES','Ines Ayari','MEDICAL STAFF','SENIORS','','R','Tunisia','[]'::jsonb,'05/03/1980',0,'0','0',0,0,0,false,'2027','0','[]'::jsonb);

INSERT INTO public.matches (opponent,match_date,competition,category,details)
VALUES
  ('ALGERIA','2026-03-04','WAFCON Qualifier','SENIORS','{"result":"2-1","venue":"Stade de Rades"}'::jsonb),
  ('MOROCCO','2026-05-22','WAFCON Qualifier','SENIORS','{"result":"0-0","venue":"Stade de Rades"}'::jsonb),
  ('EGYPT','2026-01-18','Friendly','U20','{"result":"3-2","venue":"Stade Olympique"}'::jsonb),
  ('SENEGAL','2026-08-10','Friendly','SENIORS','{"result":"1-0","venue":"Abeche"}'::jsonb);

-- ------------------------------------------------------------
-- AFTER THIS:  register one account in the portal (REGISTER button),
-- then promote it to admin by running:
--
--   UPDATE public.profiles SET role='admin', status='active' WHERE username='YOUR_USERNAME';
-- ------------------------------------------------------------