import type { Lang } from "@/lib/bingo-logic"

const en = {
  gamesTitle: "Games", gamesSub: "A little friendly competition for the staff", back: "Back",
  // hub cards
  waTitle: "Who am I?", waDesc: "Guess the player from clues. The fewer clues you need, the more points you earn.",
  bgTitle: "Match-day Bingo", bgDesc: "Lock your predictions on a 3×3 card before the match and score when they come true.",
  // who am i
  waRound: "Player {n} of {t}", waClue: "Clue {n}/{t}", waPlaceholder: "Type a name…", waGiveUp: "Give up",
  waWrong: "Not quite. Here is another clue.", waCorrect: "Correct! +{n} points", waReveal: "It was {name}",
  waNext: "Next player", waFinish: "See results", waDone: "Round complete", waScore: "Your score", waOutOf: "out of {n}",
  waAgain: "Play again", waStart: "Start", waBoard: "Top scores", waPts: "pts", waNoMatch: "No player found",
  waNoData: "Not enough player profiles to play yet. At least 5 players need a position, club, age and one more detail.",
  waPlays: "{n} plays",
  clue_position: "Position", clue_country: "Country", clue_club: "Club", clue_age: "Age", clue_height: "Height",
  clue_jersey: "Jersey number", clue_caps: "Caps", clue_goals: "Goals", clue_photo: "Photo",
  waYears: "{n} years", waLastClue: "Last clue: the photo",
  // bingo
  bgTabNext: "Next match", bgTabResults: "My results", bgTabBoard: "Leaderboard",
  bgHowTo: "Lock up to {n} squares you think will happen. Each correct square earns {p} points; a full line of locked, correct squares adds {l}.",
  bgLocked: "{n}/{max} locked", bgSave: "Save my picks", bgSaved: "Picks saved", bgSaving: "Saving…",
  bgNoFixture: "No upcoming fixtures. Schedule a match to start playing.",
  bgPractice: "Practice on a played match (no points)", bgPickMatch: "Choose a match",
  bgReveal: "Reveal the result", bgReset: "Try again", bgYes: "Happened", bgNo: "Did not happen", bgVoid: "Not enough data",
  bgMinuteHint: "Exact-minute square", bgPts: "{n} pts", bgLines: "{n} line(s)",
  bgNoResults: "No finished games yet. Your results appear here once a match you played on is recorded.",
  bgWaiting: "Waiting for the result", bgOn: "{date}",
  bgRank: "#", bgPlayer: "Player", bgCorrect: "Hits", bgLinesCol: "Lines", bgGames: "Games",
  bgBoardEmpty: "No scores yet. The table fills in once matches you played on are recorded.",
  bgDeviceOnly: "Picks are saved on this device only. Ask an admin to run supabase-games.sql to share them with the whole staff.",
  bgPracticeNote: "Practice: nothing is saved and no points are awarded.",
  bgYou: "you", bgTotal: "Total", bgResultLine: "Result: {r}",
  soundOn: "Sound on", soundOff: "Sound off", bgLineDone: "Line complete!", waTarget: "Points for this clue", bgUpTo: "Up to {n} pts",
}

const fr: typeof en = {
  gamesTitle: "Jeux", gamesSub: "Un peu de compétition amicale pour le staff", back: "Retour",
  waTitle: "Qui suis-je ?", waDesc: "Devinez la joueuse grâce aux indices. Moins il vous en faut, plus vous gagnez de points.",
  bgTitle: "Bingo du match", bgDesc: "Verrouillez vos pronostics sur une grille 3×3 avant le match et marquez des points s'ils se réalisent.",
  waRound: "Joueuse {n} sur {t}", waClue: "Indice {n}/{t}", waPlaceholder: "Tapez un nom…", waGiveUp: "Abandonner",
  waWrong: "Pas tout à fait. Voici un autre indice.", waCorrect: "Bravo ! +{n} points", waReveal: "C'était {name}",
  waNext: "Joueuse suivante", waFinish: "Voir les résultats", waDone: "Manche terminée", waScore: "Votre score", waOutOf: "sur {n}",
  waAgain: "Rejouer", waStart: "Commencer", waBoard: "Meilleurs scores", waPts: "pts", waNoMatch: "Aucune joueuse trouvée",
  waNoData: "Pas assez de fiches joueuses pour jouer. Il faut au moins 5 joueuses avec poste, club, âge et un autre détail.",
  waPlays: "{n} parties",
  clue_position: "Poste", clue_country: "Pays", clue_club: "Club", clue_age: "Âge", clue_height: "Taille",
  clue_jersey: "Numéro de maillot", clue_caps: "Sélections", clue_goals: "Buts", clue_photo: "Photo",
  waYears: "{n} ans", waLastClue: "Dernier indice : la photo",
  bgTabNext: "Prochain match", bgTabResults: "Mes résultats", bgTabBoard: "Classement",
  bgHowTo: "Verrouillez jusqu'à {n} cases qui, selon vous, vont se produire. Chaque case juste rapporte {p} points ; une ligne complète de cases verrouillées et justes ajoute {l}.",
  bgLocked: "{n}/{max} verrouillées", bgSave: "Enregistrer mes choix", bgSaved: "Choix enregistrés", bgSaving: "Enregistrement…",
  bgNoFixture: "Aucun match à venir. Programmez un match pour commencer à jouer.",
  bgPractice: "S'entraîner sur un match joué (sans points)", bgPickMatch: "Choisir un match",
  bgReveal: "Révéler le résultat", bgReset: "Réessayer", bgYes: "Réalisé", bgNo: "Non réalisé", bgVoid: "Données insuffisantes",
  bgMinuteHint: "Case à la minute près", bgPts: "{n} pts", bgLines: "{n} ligne(s)",
  bgNoResults: "Aucune partie terminée. Vos résultats apparaissent ici dès qu'un match sur lequel vous avez joué est enregistré.",
  bgWaiting: "En attente du résultat", bgOn: "{date}",
  bgRank: "#", bgPlayer: "Joueur", bgCorrect: "Justes", bgLinesCol: "Lignes", bgGames: "Parties",
  bgBoardEmpty: "Pas encore de scores. Le classement se remplit quand les matchs joués sont enregistrés.",
  bgDeviceOnly: "Les choix sont enregistrés sur cet appareil uniquement. Demandez à un admin d'exécuter supabase-games.sql pour les partager avec tout le staff.",
  bgPracticeNote: "Entraînement : rien n'est enregistré et aucun point n'est attribué.",
  bgYou: "vous", bgTotal: "Total", bgResultLine: "Résultat : {r}",
  soundOn: "Son activé", soundOff: "Son coupé", bgLineDone: "Ligne complète !", waTarget: "Points pour cet indice", bgUpTo: "Jusqu'à {n} pts",
}

const ar: typeof en = {
  gamesTitle: "ألعاب", gamesSub: "القليل من المنافسة الودية للطاقم", back: "رجوع",
  waTitle: "من أنا؟", waDesc: "خمّني اللاعبة من خلال التلميحات. كلما احتجتِ إلى تلميحات أقل، ربحتِ نقاطاً أكثر.",
  bgTitle: "بينغو المباراة", bgDesc: "ثبّت توقعاتك على بطاقة 3×3 قبل المباراة واحصل على نقاط عند تحققها.",
  waRound: "اللاعبة {n} من {t}", waClue: "التلميح {n}/{t}", waPlaceholder: "اكتب اسماً…", waGiveUp: "استسلام",
  waWrong: "ليس تماماً. إليك تلميحاً آخر.", waCorrect: "صحيح! +{n} نقطة", waReveal: "كانت {name}",
  waNext: "اللاعبة التالية", waFinish: "عرض النتائج", waDone: "انتهت الجولة", waScore: "نتيجتك", waOutOf: "من {n}",
  waAgain: "العب مجدداً", waStart: "ابدأ", waBoard: "أعلى النتائج", waPts: "نقطة", waNoMatch: "لم يتم العثور على لاعبة",
  waNoData: "لا توجد ملفات لاعبات كافية للعب بعد. يلزم 5 لاعبات على الأقل لديهن مركز ونادٍ وعمر وتفصيل آخر.",
  waPlays: "{n} مرات لعب",
  clue_position: "المركز", clue_country: "البلد", clue_club: "النادي", clue_age: "العمر", clue_height: "الطول",
  clue_jersey: "رقم القميص", clue_caps: "المباريات الدولية", clue_goals: "الأهداف", clue_photo: "الصورة",
  waYears: "{n} سنة", waLastClue: "التلميح الأخير: الصورة",
  bgTabNext: "المباراة القادمة", bgTabResults: "نتائجي", bgTabBoard: "الترتيب",
  bgHowTo: "ثبّت حتى {n} مربعات تتوقع حدوثها. كل مربع صحيح يمنحك {p} نقاط، وخط كامل من المربعات المثبتة الصحيحة يضيف {l}.",
  bgLocked: "{n}/{max} مثبتة", bgSave: "حفظ اختياراتي", bgSaved: "تم حفظ الاختيارات", bgSaving: "جارٍ الحفظ…",
  bgNoFixture: "لا توجد مباريات قادمة. برمج مباراة لتبدأ اللعب.",
  bgPractice: "تدرّب على مباراة منتهية (بدون نقاط)", bgPickMatch: "اختر مباراة",
  bgReveal: "اكشف النتيجة", bgReset: "حاول مجدداً", bgYes: "تحقق", bgNo: "لم يتحقق", bgVoid: "بيانات غير كافية",
  bgMinuteHint: "مربع بالدقيقة", bgPts: "{n} نقطة", bgLines: "{n} خط",
  bgNoResults: "لا توجد مباريات منتهية بعد. تظهر نتائجك هنا عند تسجيل مباراة شاركت فيها.",
  bgWaiting: "في انتظار النتيجة", bgOn: "{date}",
  bgRank: "#", bgPlayer: "اللاعب", bgCorrect: "الصحيحة", bgLinesCol: "الخطوط", bgGames: "المباريات",
  bgBoardEmpty: "لا توجد نتائج بعد. يمتلئ الجدول عند تسجيل المباريات التي شاركتم فيها.",
  bgDeviceOnly: "تُحفظ الاختيارات على هذا الجهاز فقط. اطلب من المشرف تشغيل supabase-games.sql لمشاركتها مع كل الطاقم.",
  bgPracticeNote: "تدريب: لا يتم حفظ أي شيء ولا تُمنح نقاط.",
  bgYou: "أنت", bgTotal: "المجموع", bgResultLine: "النتيجة: {r}",
  soundOn: "الصوت يعمل", soundOff: "الصوت متوقف", bgLineDone: "خط كامل!", waTarget: "نقاط هذا التلميح", bgUpTo: "حتى {n} نقطة",
}

export const GS: Record<Lang, typeof en> = { en, fr, ar }
export type GameStrings = typeof en
export const fmt = (s: string, v: Record<string, string | number>) => s.replace(/\{(\w+)\}/g, (_, k) => String(v[k] ?? ""))
